#!/bin/bash

# Uses Image Magick to convert test image file generated by test-srend
# From an 800x600 image with each pixel defined by RGBA values, each being a float (32) to
# a PNG.

convert -size 800x600 -define quantum:format=floating-point -depth 32 test-image-float32-800x600.rgba test-image.png